### ISSUE TITLE
Strange UInt256 conversion logic

### ISSUE THREAD

**Issue by Rexagon** [everx-labs/ever-types#28]
In case of `UInt256` was supposed to be used in big endian format, [**this**](https://github.com/tonlabs/ton-labs-types/blob/57f348658fc46179f9c0c72f3bb7dd123bd98f38/src/types.rs#L170-L177) conversion is probably incorrect. For example when converting from result of `num::BigUint::to_bytes_be`, only the most significant bytes will be filled.

This error can occur in abi-related stuff, when converting from `uint256`, which uses `num::BigUint` as value, to other code, which uses `UInt256` and raw bytes.

Possible solution will be adding an offset:
```rust
impl From<&[u8]> for UInt256 {
    fn from(value: &[u8]) -> Self {
        let mut data = [0; 32];
        let len = cmp::min(value.len(), 32);
        let offset = 32 - len;
        (0..len).for_each(|i| data[i + offset] = value[i]);
        Self(data)
    }
}
```

**Comment by yaroslavser** [comment]
Thank you for your advice. It will be implemented soon. Fee free to make new enhancements.

**Comment by bvscd** [comment]
Fixed
